CREATE SCHEMA IF NOT EXISTS Correção_Questão10Ae;

USE Correção_Questão10AA;

CREATE TABLE IF NOT EXISTS CLIENTES (
    CLIENTE_NUM INT PRIMARY KEY, 
    CLIENTE_NOME VARCHAR(50) NOT NULL, 
    CLIENTE_RUA VARCHAR(45) NOT NULL,
    CLIENTE_NUMRUA VARCHAR(45) NOT NULL,
    CLIENTE_BAIRRO VARCHAR(45) NOT NULL,
    CLIENTE_CIDADE VARCHAR(45) NOT NULL,
    CLIENTE_ESTADO VARCHAR(45) NOT NULL,
    CLIENTE_PAIS VARCHAR(30) NOT NULL,
    CLIENTE_CODPOSTAL VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS CARROS (
    CARRO_REGISTRO INT PRIMARY KEY,
    CARRO_MARCA VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS APÓLICES (
    APOLICE_NUM INT PRIMARY KEY, 
    APOLICE_VALOR DECIMAL(10,2) NOT NULL,
    CLIENTE_APÓLICES INT,  -- Coluna para a chave estrangeira
    CARRO_APÓLICES INT,     -- Coluna para a chave estrangeira
    CONSTRAINT FK_CLIENTES FOREIGN KEY (CLIENTE_APÓLICES) REFERENCES CLIENTES (CLIENTE_NUM),
    CONSTRAINT FK_CARROS FOREIGN KEY (CARRO_APÓLICES) REFERENCES CARROS (CARRO_REGISTRO)
);

CREATE TABLE IF NOT EXISTS ACIDENTES (
    CARRO_REGISTRO INT PRIMARY KEY,
    ACIDENTE_DATA DATE NOT NULL,
    ACIDENTE_HORA TIME NOT NULL,
    ACIDENTE_LOCAL TEXT NOT NULL, 
    CONSTRAINT FK_CARROS_ACIDENTES FOREIGN KEY (CARRO_REGISTRO) REFERENCES CARROS (CARRO_REGISTRO)
);

CREATE TABLE IF NOT EXISTS CARROS_CLIENTES (
    CARPR_CLIENTES INT, 
    CARPR_CARROS INT, 
    PRIMARY KEY (CARPR_CLIENTES, CARPR_CARROS),
    CONSTRAINT CARPR_FK_CLIENTES FOREIGN KEY (CARPR_CLIENTES) REFERENCES CLIENTES (CLIENTE_NUM),
    CONSTRAINT CARPR_FK_CARROS FOREIGN KEY (CARPR_CARROS) REFERENCES CARROS (CARRO_REGISTRO)
);